openapi: 3.0.0

info:
  title: KU SEEK 
  description: CRUD operations for KU SEEK
  version: 2.0.0

servers:
  - url: /api/v1

paths:
  /test/{var}:
    parameters:
      - name: var
        in: path
        required: true
        description: Variable to return
        schema:
          type: string
    get:
      summary: Returns the Variable
      operationId: controller.test_api
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  var:
                    type: string