"""modify role tables

Revision ID: 04398c34e35f
Revises: e0a60f201917
Create Date: 2025-10-19 14:34:38.870635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '04398c34e35f'
down_revision: Union[str, Sequence[str], None] = 'e0a60f201917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'company_type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('companies', 'company_industry',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('companies', 'company_website',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('companies', 'full_location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('professors', 'department',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('professors', 'position',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('professors', 'office_location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('professors', 'research_interests',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('professors', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('students', 'gpa',
               existing_type=mysql.DECIMAL(precision=3, scale=2),
               nullable=True)
    op.alter_column('students', 'interests',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'interests',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('students', 'gpa',
               existing_type=mysql.DECIMAL(precision=3, scale=2),
               nullable=False)
    op.alter_column('professors', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('professors', 'research_interests',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('professors', 'office_location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('professors', 'position',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('professors', 'department',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('companies', 'full_location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('companies', 'company_website',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('companies', 'company_industry',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('companies', 'company_type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
