"""Delete annoucement table because it doesn't need anymore, and add CompanyTags to make it better

Revision ID: 05987fc55dc6
Revises: e0a60f201917
Create Date: 2025-10-26 22:53:32.079906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '05987fc55dc6'
down_revision: Union[str, Sequence[str], None] = 'e0a60f201917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_tags',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'tag_id')
    )
    op.drop_table('announcements')
    op.add_column('companies', sa.Column('company_overview', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'company_overview')
    op.create_table('announcements',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('professor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], name=op.f('announcements_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('company_tags')
    # ### end Alembic commands ###
