"""fix autoincrement issue

Revision ID: 16882f9cb8bf
Revises: 3ce7adcbc68f
Create Date: 2025-09-09 22:22:58.169062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16882f9cb8bf'
down_revision: Union[str, Sequence[str], None] = '3ce7adcbc68f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
