"""resolve conflicts

Revision ID: 2668388b2a53
Revises: d956d870ffc5
Create Date: 2025-09-30 23:29:36.891307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2668388b2a53'
down_revision: Union[str, Sequence[str], None] = 'd956d870ffc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('type', sa.Enum('STUDENT', 'COMPANY', 'STAFF', 'PROFESSOR', name='usertypes'), nullable=False))
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('users', sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('users', 'type')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
