"""Change FK of profileskills to link with tags

Revision ID: 365c9c25e984
Revises: 703c173097da
Create Date: 2025-11-19 18:11:36.389418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365c9c25e984'
down_revision: Union[str, Sequence[str], None] = '703c173097da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted to migrate data ###
    # Drop any existing FK on profile_skills(skill_id) if present (name may differ)
    conn = op.get_bind()
    fk_row = conn.execute(
        sa.text(
            """
            SELECT CONSTRAINT_NAME
            FROM information_schema.KEY_COLUMN_USAGE
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = 'profile_skills'
              AND COLUMN_NAME = 'skill_id'
            LIMIT 1
            """
        )
    ).fetchone()
    if fk_row:
        fk_name = fk_row[0]
        try:
            op.drop_constraint(fk_name, 'profile_skills', type_='foreignkey')
        except Exception:
            # If drop fails, continue - we'll attempt to create the correct FK later
            pass

    # 1) Ensure every distinct term name exists in `tags`.
    op.execute(
        """
        INSERT INTO tags (name)
        SELECT DISTINCT t.name
        FROM terms t
        LEFT JOIN tags tg ON tg.name = t.name
        WHERE tg.name IS NULL
        """
    )

    # 2) Remap profile_skills.skill_id to point to the newly created tag ids
    #    Join through terms by name so old integer term ids are replaced
    #    with the corresponding tags.id values.
    op.execute(
        """
        UPDATE profile_skills ps
        JOIN terms t ON ps.skill_id = t.id
        JOIN tags tg ON tg.name = t.name
        SET ps.skill_id = tg.id
        """
    )

    # 3) Now create the new foreign key constraint to tags
    op.create_foreign_key(None, 'profile_skills', 'tags', ['skill_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile_skills', type_='foreignkey')
    op.create_foreign_key(op.f('profile_skills_ibfk_1'), 'profile_skills', 'terms', ['skill_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
