"""initialize database

Revision ID: 3ce7adcbc68f
Revises: 
Create Date: 2025-09-09 22:16:01.687632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3ce7adcbc68f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('google_uid', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tokens',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('refresh_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['User.id'], ),
    sa.PrimaryKeyConstraint('refresh_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tokens')
    op.drop_table('tasks')
    op.drop_table('User')
    # ### end Alembic commands ###
