"""add request models

Revision ID: 703c173097da
Revises: cc872923e7ba
Create Date: 2025-11-16 13:35:39.795370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '703c173097da'
down_revision: Union[str, Sequence[str], None] = 'cc872923e7ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('requested_type', sa.Enum('STUDENT', 'COMPANY', 'STAFF', 'PROFESSOR', 'ADMIN', name='usertypes'), nullable=False),
    sa.Column('status', sa.Enum('APPROVED', 'PENDING', 'DENIED', name='requeststatustypes'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('verification_document', sa.Uuid(), nullable=True),
    sa.Column('denial_reason', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_document'], ['files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('APPROVED', 'PENDING', 'DENIED', name='requeststatustypes'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('denial_reason', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_requests')
    op.drop_table('user_requests')
    # ### end Alembic commands ###
