"""update user table

Revision ID: 7e08f369d641
Revises: 16882f9cb8bf
Create Date: 2025-09-29 13:44:36.034086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7e08f369d641'
down_revision: Union[str, Sequence[str], None] = '16882f9cb8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('User', sa.Column('type', sa.Enum('STUDENT', 'COMPANY', 'STAFF', 'PROFESSOR', name='usertypes'), nullable=False))
    op.drop_column('User', 'password')
    op.drop_column('User', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('password', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('User', 'type')
    op.drop_column('User', 'is_verified')
    # ### end Alembic commands ###
