"""Change student_id, professor_id, company_id in profile model to be integer

Revision ID: b0502db5e9f7
Revises: 2668388b2a53
Create Date: 2025-10-07 23:06:27.861878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0502db5e9f7'
down_revision: Union[str, Sequence[str], None] = '2668388b2a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
