"""update application table

Revision ID: cba55e2c92c0
Revises: 2668388b2a53
Create Date: 2025-10-07 19:06:23.980965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cba55e2c92c0'
down_revision: Union[str, Sequence[str], None] = '2668388b2a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('job_applications', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('job_applications', sa.Column('contact_email', sa.String(length=255), nullable=False))
    op.add_column('job_applications', sa.Column('years_of_experience', sa.String(length=255), nullable=False))
    op.add_column('job_applications', sa.Column('expected_salary', sa.String(length=255), nullable=False))
    op.drop_column('job_applications', 'additional_document')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('additional_document', mysql.VARCHAR(length=500), nullable=True))
    op.drop_column('job_applications', 'expected_salary')
    op.drop_column('job_applications', 'years_of_experience')
    op.drop_column('job_applications', 'contact_email')
    op.drop_column('job_applications', 'last_name')
    op.drop_column('job_applications', 'first_name')
    # ### end Alembic commands ###
