"""update user and add request models

Revision ID: cc872923e7ba
Revises: 04398c34e35f
Create Date: 2025-11-16 12:50:15.955133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc872923e7ba'
down_revision: Union[str, Sequence[str], None] = '04398c34e35f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('Tokens_ibfk_1'), 'Tokens', type_='foreignkey')
    op.create_foreign_key(None, 'Tokens', 'users', ['uid'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('password', sa.String(length=200), nullable=True))
    op.alter_column('users', 'google_uid',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['google_uid'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'google_uid',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'password')
    op.drop_constraint(None, 'Tokens', type_='foreignkey')
    op.create_foreign_key(op.f('Tokens_ibfk_1'), 'Tokens', 'users', ['uid'], ['id'])
    # ### end Alembic commands ###
