"""Delete edu id in Students, put user id in Educations

Revision ID: cf0444674ccc
Revises: 04398c34e35f
Create Date: 2025-11-08 23:23:56.935618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cf0444674ccc'
down_revision: Union[str, Sequence[str], None] = '04398c34e35f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Create 'Tokens' only if it does not already exist (avoid duplicate-create errors)
    if not inspector.has_table('Tokens'):
        op.create_table(
            'Tokens',
            sa.Column('uid', sa.Uuid(), nullable=False),
            sa.Column('refresh_id', mysql.INTEGER(unsigned=True), nullable=False),
            sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
            sa.PrimaryKeyConstraint('refresh_id')
        )

    # Drop legacy lowercase 'tokens' table if present
    if inspector.has_table('tokens'):
        op.drop_table('tokens')
    op.add_column('educations', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'educations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('students_ibfk_1'), 'students', type_='foreignkey')
    op.drop_column('students', 'education_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('education_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('students_ibfk_1'), 'students', 'educations', ['education_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'educations', type_='foreignkey')
    op.drop_column('educations', 'user_id')
    op.create_table('tokens',
    sa.Column('uid', mysql.CHAR(length=32), nullable=False),
    sa.Column('refresh_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], name=op.f('tokens_ibfk_1')),
    sa.PrimaryKeyConstraint('refresh_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Tokens')
    # ### end Alembic commands ###
