"""modify mail_record to include html_body and text_body

Revision ID: cfdb9c54cfab
Revises: 82d057529a83
Create Date: 2025-11-03 21:47:07.132757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cfdb9c54cfab'
down_revision: Union[str, Sequence[str], None] = '82d057529a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail_records', sa.Column('text_body', sa.Text(), nullable=False))
    op.add_column('mail_records', sa.Column('html_body', sa.Text(), nullable=False))
    op.drop_column('mail_records', 'body')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail_records', sa.Column('body', mysql.TEXT(), nullable=False))
    op.drop_column('mail_records', 'html_body')
    op.drop_column('mail_records', 'text_body')
    # ### end Alembic commands ###
